import type { WelcomePack } from './types'

export const aaResinSteps: WelcomePack = {
  slug: 'aa-resin-steps',
  client: {
    name: 'AA Resin Steps',
    ownerFirstName: 'Zeeshan',
    industry: 'trades',
    industryNoun: 'trades',
    city: 'Glasgow',
    deliveryVerb: 'build resin steps',
    signedDateRelative: 'last Monday',
    launchDateRelative: 'Friday afternoon',
    launchDate: '24 April 2026',
    monthYear: 'April 2026',
    nextKeyDay: 'Monday',
  },
  deal: {
    weeklyRetainer: 125,
    weeklyAdSpend: 100,
    targetRevenueLow: 8000,
    targetRevenueHigh: 10000,
    clientSpecificInclusions: [
      'Logo refresh included this month',
      'Past-client testimonial outreach included in month 2',
    ],
  },
  liveAd: {
    campaignName: 'Month 1 Campaign',
    campaignType: 'Advantage+ Leads',
    dailyBudget: 14,
    adSetName: 'AA Resin Steps - Launch - Apr 26',
    fbPage: 'AA Resin Steps',
    igHandle: '@aaresinsteps',
    location: 'Glasgow + 40km radius',
    ageRange: '30 to 65+',
    gender: 'All',
    interests: [
      'Home and garden',
      'Home repair',
      'Homeowner association',
      'Property',
      'Home improvement',
    ],
    primaryText:
      'Resin steps that last 20 years.\n\nAlso doing resin driveways, patios and pathways. Non-slip. Vuba approved. Scotland-wide.\n\nTap below for a free quote in 60 seconds.',
    headline: 'Glasgow resin specialists',
    description: 'Free quote. 24-hr callback.',
    ctaButton: 'Get Quote',
    leadFormFields: [
      'Full name',
      'Postcode',
      'Email',
      'Phone',
      'What do they need done? (short answer)',
      'Photos of the area (optional)',
    ],
    knownQuirks: [
      'Your ad account timezone is set to PDT (California) instead of UK. This was locked in before launch. It does not affect performance, only the timestamps in reports are 8 hours behind. We accept this for now and fix it next account refresh.',
    ],
    thisWeekAdditions: [
      '2 to 3 more creative variants (different photos, different angles)',
      '3 to 5 of your existing Instagram posts as "boosted post" style ads',
      'The finalised logo across all assets',
      'A renamed lead form (currently called Untitled form, cosmetic)',
    ],
  },
  algorithm: {
    weeklyReach: '4,000',
    weeklyEngagements: '60',
    weeklyLeads: '5 to 10',
  },
  leadHandling: {
    firstReply:
      "Hi [name], thanks for the enquiry through our ad. I'm Zeeshan, the owner. I can come out for a free quote this week. What's the easiest day for you, weekday or weekend? I'll bring samples and a price.",
    keyPromise: 'a free quote',
    industrySpecificDetail: 'a bigger photo',
    industryPreQuoteStep: 'seen the site',
    day2Followup:
      "Hi [name], just checking you got my message. Quick answers if it helps. Resin lasts 15-20 years, dries in 24 hours, non-slip, won't damage stone. Want to lock in a free quote this week?",
    day5Followup:
      'Hi [name], last check from us. Slots filling up next week so wanted to give you the heads up before they go. Still keen?',
  },
  targets: {
    week1to2Leads: '1 to 3',
    week3to4Leads: '3 to 5',
    month1AdSpend: 400,
    month1Jobs: '3 to 6',
    month2Leads: '5 to 10',
    month3Leads: '8 to 15',
    seasonalAngle: 'summer driveway demand peaks in May to July',
  },
  asks: {
    thisWeek: [
      { text: 'Card on Meta confirmed working', done: true },
      { text: 'Add me as admin on Facebook Page AA Resin Steps (lets me build / fix without bothering you)', done: true },
      { text: 'Check you can log into Meta Ads Manager on your phone' },
      { text: 'Send a list of the last 10 to 20 happy customers (name + phone or email is fine)' },
    ],
    next2Weeks: [
      { text: '5 to 10 photos of recent jobs (before/after preferred, phone quality is fine)', done: true },
      { text: '1 short video of a finished job (vertical, 30 to 60 seconds, walking through it)', done: true },
      { text: 'Pricing ranges per job type so I can pre-qualify leads (driveway / steps / patio)' },
      { text: 'Confirm you are happy with the new logo when I send it' },
    ],
    faqGaps: [
      'Exact price ranges per job type?',
      'Minimum and maximum job size?',
      'Do you work in winter? Temperature cutoff?',
      "Warranty - what's covered, what's not?",
      'Do you handle prep (old driveway removal)?',
      'Is planning permission ever needed?',
      'Colour options?',
      'Do you fix damaged resin from other installers?',
      'Can resin go over old concrete, tarmac, block paving?',
    ],
    photoGuidance: 'before/after preferred, phone quality is fine',
    videoGuidance: 'vertical, 30 to 60 seconds, walking through it',
  },
  faq: [
    { q: 'How long does resin last?', a: '15 to 20 years if maintained', adHeadline: '20-year driveway. 1-day install.' },
    { q: 'Does it improve curb appeal?', a: 'Yes' },
    { q: 'Is it non-slip?', a: 'Yes', adHeadline: 'Non-slip resin. Scotland-weather proof.' },
    { q: 'Longer lasting than tiles?', a: 'Yes, by 10 years', adHeadline: 'Lasts 10 years longer than tiles.' },
    { q: 'Does it discolour natural stone?', a: 'No', adHeadline: "Won't discolour your stone. Dries in 24 hours." },
    { q: 'How long to dry?', a: '24 hours, weather dependent' },
    { q: 'Can you power wash it?', a: 'Yes, light power wash only' },
  ],
  llmSearchExample: 'best resin driveways near Glasgow',
  roadmap: {
    keyLandingPage: 'Free Quote landing page (matches the ad funnel)',
    websiteLocalPages: ['Glasgow', 'Bearsden', 'East Kilbride', 'Lanarkshire'],
    expansionCity1: 'Edinburgh',
    expansionCity2: 'Aberdeen',
    year1RevenueLow: 15000,
    year1RevenueHigh: 25000,
    teamGrowthGoal: '2 install crews (you train one, you hire one)',
  },
}
