// trigger/jobs/index.ts
// Re-export all tasks for Trigger.dev to discover
export { qualifyLeadTask } from './qualify-lead'
export { speedToLeadTask } from './speed-to-lead'
export { aiConversationTask } from './ai-conversation'
export { aiWhatsAppReplyTask } from './ai-whatsapp-reply'
export { syncMetaAdsTask, manualSyncMetaAdsTask } from './sync-meta-ads'
export { syncGoogleAdsTask, manualSyncGoogleAdsTask } from './sync-google-ads'
export { syncTikTokAdsTask, manualSyncTikTokAdsTask } from './sync-tiktok-ads'
export { weeklyReportTask } from './weekly-report'
export { runAutomationTask } from './run-automation'
export { sendReviewRequestTask } from './send-review-request'
export { checkMembershipExpiryTask } from './check-membership-expiry'
export { nurturePipelineTask, nurturePipelineSchedule } from './nurture-pipeline'
export { autoCallLeadTask } from './auto-call-lead'
